import re
from enum import Enum
from pathlib import Path
from typing import Any


class FontSize(Enum):
    """Font size options for the UI."""
    VERY_SMALL = 15
    SMALL = 18
    MEDIUM = 21
    LARGE = 24
    VERY_LARGE = 27
    ULTRA_LARGE = 30


class Settings:
    """
    Configuration for the paper generator pipeline.
    
    Note: MLX embedding models are NOT supported by LM Studio yet, use GGUF instead :(
    See https://github.com/lmstudio-ai/lmstudio-bug-tracker/issues/808
    
    Settings are saved directly to this file.
    """
    
    # Context Analysis Phase
    CODE_ANALYSIS_MODEL = "qwen/qwen3-next-80b"  
    PAPER_CONCEPTION_MODEL = "qwen/qwen3-next-80b"  
    
    # Paper Search Phase
    LITERATURE_SEARCH_MODEL = "qwen/qwen3-next-80b"  
    PAPER_RANKING_EMBEDDING_MODEL = "text-embedding-qwen3-embedding-4b@q5_0"  # Must be an embedding model!
    
    # Hypothesis Generation Phase
    HYPOTHESIS_BUILDER_MODEL = "qwen/qwen3-next-80b"
    
    # Experimentation Phase
    EXPERIMENT_PLAN_MODEL = "qwen/qwen3-next-80b"
    EXPERIMENT_CODE_WRITE_MODEL = "qwen/qwen3-next-80b"  
    EXPERIMENT_VALIDATION_MODEL = "qwen/qwen3-next-80b" 
    EXPERIMENT_PLOT_CAPTION_MODEL = "qwen3-vl-32b-instruct-mlx"  # Must be a VISION model!
    EXPERIMENT_VERDICT_MODEL = "qwen/qwen3-next-80b"
    
    # Paper Writing Phase
    PAPER_INDEXING_EMBEDDING_MODEL = "text-embedding-qwen3-embedding-4b@q5_0"  # Must be an embedding model!
    PAPER_WRITING_MODEL = "qwen/qwen3-next-80b"
    GENERATE_ACKNOWLEDGEMENTS = True

    # LaTeX Generation Phase
    LATEX_GENERATION_MODEL = "qwen/qwen3-next-80b"

    # UI Settings
    FONT_SIZE = FontSize.SMALL
    DARK_MODE = True

    # API related
    SEMANTIC_SCHOLAR_API_KEY = ""  # Optional Semantic Scholar API key for better rate limits
    UNPAYWALL_EMAIL = ""  # Email for Unpaywall API (for finding free PDFs)

    # LaTeX Data
    LATEX_TEMPLATE = "jair"  # Template directory name from latex_templates/
    LATEX_TITLE = ""  # If empty, title will be generated by LLM

    LATEX_AUTHORS = [
        {
            "name": "Author 1",
            "affiliation": "University of Test",
            "department": "Department of Computer Science",
            "city": "Mannheim",
            "country": "Germany",
            "address": "Some cool place",
            "email": "author1@university.com"
        },
    ]

    @classmethod
    def save_to_file(cls) -> None:
        """Save current settings by rewriting this Python file."""
        settings_file = Path(__file__)
        
        try:
            content = settings_file.read_text(encoding='utf-8')
            
            # Settings to save with their current values
            settings_to_save = {
                "CODE_ANALYSIS_MODEL": cls.CODE_ANALYSIS_MODEL,
                "PAPER_CONCEPTION_MODEL": cls.PAPER_CONCEPTION_MODEL,
                "LITERATURE_SEARCH_MODEL": cls.LITERATURE_SEARCH_MODEL,
                "PAPER_RANKING_EMBEDDING_MODEL": cls.PAPER_RANKING_EMBEDDING_MODEL,
                "HYPOTHESIS_BUILDER_MODEL": cls.HYPOTHESIS_BUILDER_MODEL,
                "EXPERIMENT_PLAN_MODEL": cls.EXPERIMENT_PLAN_MODEL,
                "EXPERIMENT_CODE_WRITE_MODEL": cls.EXPERIMENT_CODE_WRITE_MODEL,
                "EXPERIMENT_VALIDATION_MODEL": cls.EXPERIMENT_VALIDATION_MODEL,
                "EXPERIMENT_PLOT_CAPTION_MODEL": cls.EXPERIMENT_PLOT_CAPTION_MODEL,
                "EXPERIMENT_VERDICT_MODEL": cls.EXPERIMENT_VERDICT_MODEL,
                "PAPER_INDEXING_EMBEDDING_MODEL": cls.PAPER_INDEXING_EMBEDDING_MODEL,
                "PAPER_WRITING_MODEL": cls.PAPER_WRITING_MODEL,
                "LATEX_GENERATION_MODEL": cls.LATEX_GENERATION_MODEL,
                "FONT_SIZE": cls.FONT_SIZE.name,
                "DARK_MODE": cls.DARK_MODE,
                "SEMANTIC_SCHOLAR_API_KEY": cls.SEMANTIC_SCHOLAR_API_KEY,
                "UNPAYWALL_EMAIL": cls.UNPAYWALL_EMAIL,
                "LATEX_TITLE": cls.LATEX_TITLE,
                "LATEX_TEMPLATE": cls.LATEX_TEMPLATE,
            }
            
            # Update string values
            for key, value in settings_to_save.items():
                if key == "FONT_SIZE":
                    # Handle FontSize enum: FONT_SIZE = FontSize.SMALL
                    pattern = rf'(\s+{key}\s*=\s*)FontSize\.\w+'
                    replacement = rf'\1FontSize.{value}'
                    content = re.sub(pattern, replacement, content)
                elif isinstance(value, str):
                    # Match: KEY = "value" or KEY = ""
                    pattern = rf'(\s+{key}\s*=\s*)"[^"]*"'
                    replacement = rf'\1"{value}"'
                    content = re.sub(pattern, replacement, content)
                elif isinstance(value, bool):
                    # Match: KEY = True or KEY = False
                    pattern = rf'(\s+{key}\s*=\s*)(True|False)'
                    replacement = rf'\1{value}'
                    content = re.sub(pattern, replacement, content)
                elif isinstance(value, int):
                    # Match: KEY = number
                    pattern = rf'(\s+{key}\s*=\s*)\d+'
                    replacement = rf'\1{value}'
                    content = re.sub(pattern, replacement, content)
            
            # Handle LATEX_AUTHORS (complex list of dicts)
            authors_str = _format_authors(cls.LATEX_AUTHORS)
            # Match the entire LATEX_AUTHORS block
            pattern = r'(\s+LATEX_AUTHORS\s*=\s*)\[[\s\S]*?\n    \]'
            replacement = rf'\1{authors_str}'
            content = re.sub(pattern, replacement, content)
            
            settings_file.write_text(content, encoding='utf-8')
            print(f"[Settings] Saved settings to {settings_file}")
        except Exception as e:
            print(f"[Settings] Failed to save settings: {e}")


def _format_authors(authors: list) -> str:
    """Format authors list as Python code."""
    if not authors:
        return "[]"
    
    lines = ["["]
    for i, author in enumerate(authors):
        lines.append("        {")
        lines.append(f'            "name": "{author.get("name", "")}",')
        lines.append(f'            "affiliation": "{author.get("affiliation", "")}",')
        lines.append(f'            "department": "{author.get("department", "")}",')
        lines.append(f'            "city": "{author.get("city", "")}",')
        lines.append(f'            "country": "{author.get("country", "")}",')
        lines.append(f'            "address": "{author.get("address", "")}",')
        lines.append(f'            "email": "{author.get("email", "")}"')
        if i < len(authors) - 1:
            lines.append("        },")
        else:
            lines.append("        },")
    lines.append("    ]")
    return "\n".join(lines)


def get_available_templates() -> list[str]:
    """Discover available LaTeX templates.
    
    Scans latex_templates/ directory for valid template folders.
    A valid template has a paper.tex file and Makefile.
    
    Returns:
        List of template directory names (e.g., ['ieee_conference', 'jair'])
    """
    templates_dir = Path(__file__).parent / "latex_templates"
    
    if not templates_dir.exists():
        return []
    
    templates = []
    for item in sorted(templates_dir.iterdir()):
        if item.is_dir():
            paper_tex = item / "paper.tex"
            makefile = item / "Makefile"
            if paper_tex.exists() and makefile.exists():
                templates.append(item.name)
    
    return templates

