from .start_screen import StartScreen
from .settings_screen import SettingsScreen
from .paper_concept_screen import PaperConceptScreen
from .literature_search_screen import LiteratureSearchScreen
from .hypothesis_screen import HypothesisScreen
from .experiment_plan_screen import ExperimentPlanScreen
from .experiment_results_screen import ExperimentResultsScreen
from .paper_draft_screen import PaperDraftScreen
from .result_screen import ResultScreen
from .style_guidelines_screen import SectionGuidelinesScreen
from .writing_prompts_screen import WritingPromptsScreen

