from .settings_screen import SettingsScreen
from .user_requirements_screen import UserRequirementsScreen
from .paper_selection_screen import PaperSelectionScreen
from .hypothesis_screen import HypothesisScreen
from .experimentation_plan_screen import ExperimentationPlanScreen
from .result_screen import ResultScreen
